version: '3.9'

services:
  api-gateway:
    image: nginx:alpine
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - user-service
      - product-service

  user-service:
    build:
      context: ./user-service
      dockerfile: ../Dockerfile
    environment:
      DB_HOST: db-users
      DB_NAME: usersdb
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - db-users

  db-users:
    image: postgres:13
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - userdbdata:/var/lib/postgresql/data

  product-service:
    build:
      context: ./product-service
      dockerfile: ../Dockerfile
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis

  redis:
    image: redis:7
    volumes:
      - redisdata:/data

volumes:
  userdbdata:
  redisdata:
