version: '3.9'

services:
  api-gateway:
    image: nginx:alpine
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - order-service
      - user-service
      - product-service

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    environment:
      DB_HOST: db-orders
      DB_NAME: ordersdb
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - db-orders

  db-orders:
    image: postgres:13
    environment:
      POSTGRES_DB: ordersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - orderdbdata:/var/lib/postgresql/data

  user-service:
    build:
      context: ./user-service
    environment:
      DB_HOST: db-users
      DB_NAME: usersdb
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - db-users

  db-users:
    image: postgres:13
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - usersdbdata:/var/lib/postgresql/data

  product-service:
    build:
      context: ./product-service
    environment:
      REDIS_HOST: redis-products
    depends_on:
      - redis-products

  redis-products:
    image: redis:alpine
    volumes:
      - redisdata:/data

volumes:
  orderdbdata:
  usersdbdata:
  redisdata:
